language: python
python:
  - 2.7
  - 3.6

os: linux
sudo: required

install:
  - sudo apt-get install redis-server
  - python setup.py install

before_script:
  - sudo redis-server &

script:
  - nosetests . -v

notifications:
  email: false
