language: python
python:
  - 2.7
  - 3.6

os: linux
sudo: required

install:
  - sudo apt-get install redis-server
  - pip install redis

before_script:
  - sudo redis-server &

script:
  - python test.py

notifications:
  email: false
